function result = run(options)
%RUN Audit the published Saito conditions; optionally run a surrogate.
%   RESULT = PAPERSTUDIES.SAITO.RUN() is fast and deterministic. It loads
%   the exact public tables, builds all four Table-4 states, and generates
%   the 15/225 uncertainty grids without propagating a trajectory.
%
%   RESULT = ...RUN(STRUCT('forward',true)) additionally sends one 150 kg
%   constant-Cd/L/D case through the existing Reentry_Propagator. That
%   result is explicitly a reduced surrogate, not a numerical reproduction
%   of the proprietary HSRC aerodynamic/guidance simulation.

    if nargin < 1 || isempty(options)
        options = struct();
    end
    if ~isstruct(options) || ~isscalar(options)
        error('paperstudies:saito:run:InvalidOptions', ...
              'options must be a scalar struct.');
    end

    cfg = paperstudies.saito.config();
    defaults = struct( ...
        'forward', false, ...
        'entry_case', 1, ...
        'density_scale', 1.0, ...
        'cd_scale', 1.0, ...
        'ld', cfg.surrogate.ld, ...
        'dt_s', cfg.surrogate.dt_s, ...
        'max_time_s', cfg.surrogate.max_time_s);
    options = merge_options(defaults, options);
    validate_options(options);

    result.study = cfg.study;
    result.status = paperstudies.saito.status();
    result.tables = cfg.tables;
    result.published_switches_and_rates = cfg.published;
    result.table6_deorbit_grid = paperstudies.saito.table6_deorbit_grid(cfg);
    result.explicit_grid = paperstudies.saito.explicit_uncertainty_grid(cfg);
    result.rpc_grid = paperstudies.saito.rpc_uncertainty_grid(cfg);

    entries = repmat(paperstudies.saito.entry_state(1, cfg), 1, 4);
    for case_id = 1:4
        entries(case_id) = paperstudies.saito.entry_state(case_id, cfg);
    end
    result.entry_cases = entries;
    range_diagnostics = [entries.range_diagnostic];
    result.range_to_go_inconsistency_detected = ...
        any([range_diagnostics.inconsistency_detected]);

    % Deterministic examples exercise the public algebra without inventing
    % missing guidance schedules or proprietary aerodynamic inputs.
    example.R_guidance = paperstudies.saito.eq16_guidance_range( ...
        100, -2, 3, 2.5, 0.1, -120, -130);
    example.ld_command = paperstudies.saito.eq13_ld_command( ...
        0.25, 0.001, 120, example.R_guidance);
    example.R_ref_eq17_printed = paperstudies.saito.eq17_reference_range( ...
        0.25, 1000, cfg.conventions.gravity_m_s2, cfg.conventions.earth_radius_m);
    example.D_ref_eq18 = paperstudies.saito.eq18_reference_drag( ...
        0.25, 1000, cfg.conventions.gravity_m_s2, cfg.conventions.earth_radius_m);
    example.hdot_ref_eq19 = paperstudies.saito.eq19_reference_altitude_rate( ...
        0.25, 8000, 7000);
    example.F1_eq20 = paperstudies.saito.eq20_gain_F1( ...
        2, 1000, cfg.conventions.gravity_m_s2, cfg.conventions.earth_radius_m);
    example.F2_eq21 = paperstudies.saito.eq21_gain_F2(3, 4, 0.25);
    example.F3_eq22 = paperstudies.saito.eq22_gain_F3(5, 4, 0.25);
    example.eq17_to_eq22_classification = "SYNTHETIC_INPUTS_CONVENTION_REQUIRED";
    [example.bank_eq15_rad, example.bank_eq15_cosine] = ...
        paperstudies.saito.eq15_bank_command(0.125, 0.25);
    [example.bank_eq23_rad, example.bank_eq23_cosine] = ...
        paperstudies.saito.eq23_rpc_bank_command( ...
            deg2rad(60), deg2rad(10), 95, 100, 90);
    example.filter_eq24 = paperstudies.saito.eq24_fading_filter(1, 0.9, 1.1);
    example.bank_eq25_rad = paperstudies.saito.eq25_terminal_bank_secant( ...
        0, 1, 10, -5);
    result.equation_examples = example;

    if options.forward
        result.forward = run_forward_surrogate(cfg, entries(options.entry_case), options);
    else
        result.forward = struct( ...
            'executed', false, ...
            'classification', "SURROGATE_ONLY", ...
            'numeric_paper_reproduction', false, ...
            'reason', "Disabled by default; set options.forward=true to run the reduced trajectory.");
    end
end

function options = merge_options(defaults, supplied)
    options = defaults;
    names = fieldnames(supplied);
    allowed = fieldnames(defaults);
    for index = 1:numel(names)
        if ~any(strcmp(names{index}, allowed))
            error('paperstudies:saito:run:UnknownOption', ...
                  'Unknown option: %s', names{index});
        end
        options.(names{index}) = supplied.(names{index});
    end
end

function validate_options(options)
    if ~(islogical(options.forward) || isnumeric(options.forward)) || ...
            ~isscalar(options.forward) || ~isfinite(double(options.forward))
        error('paperstudies:saito:run:InvalidForward', ...
              'forward must be a finite logical scalar.');
    end
    if ~isscalar(options.entry_case) || options.entry_case ~= fix(options.entry_case) || ...
            options.entry_case < 1 || options.entry_case > 4
        error('paperstudies:saito:run:InvalidEntryCase', ...
              'entry_case must be an integer from 1 through 4.');
    end
    positive_names = {'density_scale','cd_scale','dt_s','max_time_s'};
    for index = 1:numel(positive_names)
        value = options.(positive_names{index});
        if ~isscalar(value) || ~isfinite(value) || value <= 0
            error('paperstudies:saito:run:InvalidPositiveOption', ...
                  '%s must be a finite positive scalar.', positive_names{index});
        end
    end
    if ~isscalar(options.ld) || ~isfinite(options.ld) || options.ld < 0
        error('paperstudies:saito:run:InvalidLD', ...
              'ld must be a finite nonnegative scalar.');
    end
end

function forward = run_forward_surrogate(cfg, entry, options)
    if exist('Mission_Config', 'file') ~= 2 || exist('Reentry_Propagator', 'file') ~= 2
        error('paperstudies:saito:run:MissingProjectPropagator', ...
              'Mission_Config and Reentry_Propagator must be on the MATLAB path.');
    end

    sys = Mission_Config("LEGACY_CAPSULE_60KG");
    sys.reentry_vehicle.vehicle_mode = "CAPSULE";
    sys.reentry_vehicle.gravity_model = "CENTRAL_SPHERICAL";
    sys.reentry_vehicle.capsule.mass_kg = cfg.surrogate.mass_kg;
    sys.reentry_vehicle.capsule.aero_model = "PAPER_CAPSULE_REDUCED";
    sys.reentry_vehicle.capsule.nominal_ld = options.ld;
    sys.reentry_vehicle.capsule.trim_aoa_deg = cfg.surrogate.trim_aoa_deg;
    sys.reentry_vehicle.capsule.parachute_deploy_speed_m_s = ...
        cfg.published.reentry.parachute_deploy_speed_m_s;
    sys.reentry_vehicle.capsule.altitude_termination_enabled = false;
    sys.reentry_vehicle.capsule.safety_floor_altitude_m = 0;
    sys.environment.atmospheric_drag.use_matlab_atmosisa = false;
    sys.environment.atmospheric_drag.co_rotate_atmosphere = true;
    sys.environment.atmospheric_drag.earth_rotation_rad_s = ...
        cfg.conventions.earth_rotation_rad_s;

    params = struct( ...
        'vehicle_mode', "CAPSULE", ...
        'separation_mode', "ENTRY_INTERFACE", ...
        'capsule_mass_kg', cfg.surrogate.mass_kg, ...
        'reference_area_m2', cfg.surrogate.reference_area_m2, ...
        'cd', cfg.surrogate.cd, ...
        'nominal_ld', options.ld, ...
        'aoa_deg', cfg.surrogate.trim_aoa_deg, ...
        'bank_angle_deg', 0, ...
        'lift_enabled', true, ...
        'gravity_model', "CENTRAL_SPHERICAL", ...
        'density_scale', options.density_scale, ...
        'cd_scale', options.cd_scale, ...
        'dt', options.dt_s, ...
        'max_time', options.max_time_s);

    [X_final, ~, hist, summary] = Reentry_Propagator( ...
        sys, entry.X_eci_14, [], 0, params);

    forward.executed = true;
    forward.classification = "SURROGATE_ONLY";
    forward.numeric_paper_reproduction = false;
    forward.model = cfg.surrogate.model;
    forward.atmosphere_implementation = cfg.surrogate.atmosphere_model;
    forward.assumptions = struct( ...
        'mass_kg', cfg.surrogate.mass_kg, ...
        'reference_area_m2', cfg.surrogate.reference_area_m2, ...
        'drag_coefficient', cfg.surrogate.cd, ...
        'lift_to_drag_ratio', options.ld, ...
        'trim_aoa_deg', cfg.surrogate.trim_aoa_deg, ...
        'bank_angle_deg', 0, ...
        'density_scale', options.density_scale, ...
        'drag_coefficient_scale', options.cd_scale, ...
        'atmosphere', cfg.surrogate.atmosphere_model, ...
        'heating', cfg.surrogate.heating_model);
    forward.missing_proprietary_aerodynamics = true;
    forward.full_guidance_implemented = false;
    forward.heating_comparable_to_paper_eq28 = false;
    forward.entry_case = entry.case_id;
    forward.options = options;
    forward.final_state = X_final;
    forward.history = hist;
    forward.summary = summary;
end
