function cfg = configure(sys, overrides)
%CONFIGURE Resolve defaults, optimizer JSON, run overrides, and environment.
% Scenario/physical constants come from sys; run settings cannot overwrite them.
run_cfg = mission.merge_settings(Mission_Run_Config(sys), overrides);
sys = apply_run_config_to_sys(sys, run_cfg);
mission_cfg = mission.load_optimizer_config(sys, run_cfg);
% Optimizer artifacts supply manoeuvre candidates, never physical authority.
sys = apply_run_config_to_sys(sys, run_cfg);
sys = apply_environment_env_overrides(sys, run_cfg);
sys = refresh_derived_sys(sys);
sys_orbit = sys;
print_environment_config(sys);
sys = apply_pre_berthing_drag_scope(sys_orbit, run_cfg);
warn_if_mission_json_environment_mismatch(mission_cfg, sys);

% Default Phase 1 custom-maneuver settings. A JSON config exported by the
% Python optimizer can override these values without editing this script.
custom_params = struct();

% Parameters for CUSTOM_IMPULSE mode. These are normally generated by the
% Python shooting optimizer.
% custom_params.phase_angle = deg2rad(3.8242);        % [rad]
% custom_params.delta_v     = 57.9955;                % [m/s]
% custom_params.gamma       = deg2rad(0.076877);      % [rad]

custom_params.phase_angle = deg2rad(3.5663);        % [rad]
custom_params.delta_v     = 64.2342;                % [m/s]
custom_params.gamma       = deg2rad(-1.416);        % [rad]

custom_params.phase_angle_unit = "rad"; % "rad" or "deg"
custom_params.gamma_unit       = "rad"; % "rad" or "deg"

% Maneuver execution model for the custom phased maneuver.
% Use "IMPULSIVE" for the legacy instantaneous delta-V model or
% "FINITE_BURN" to execute the same delta-V over a finite-duration firing.
% phase_angle, delta_v, and gamma parameters.
custom_params.burn_model = sys.maneuver.default_burn_model;
custom_params.burn_direction_mode = sys.maneuver.direction_mode;
custom_params.finite_burn_thrust = sys.maneuver.finite_burn_thrust; % [N]
custom_params.finite_burn_isp = sys.maneuver.finite_burn_isp;       % [s]
custom_params.dt_burn = sys.maneuver.finite_burn_dt;                % [s]
custom_params.max_single_burn_duration = sys.maneuver.max_single_burn_duration; % [s]
custom_params.max_single_burn_delta_v = sys.maneuver.max_single_burn_delta_v;   % [m/s]
custom_params.use_thrust_noise = get_run_bool_field(run_cfg, {'maneuver','use_thrust_noise'}, false);
custom_params.multi_hohmann_legs = []; % Used only when phasing_mode is explicitly MULTI_HOHMANN.

% Phase 1 target relative position in the target LVLH frame [m].
custom_params.desired_rel_lvlh = [0; -5000; 0];

% Event detection and propagation settings.
custom_params.time_step = 10;           % [s] nominal propagation step
custom_params.dt_phase = 5;             % [s] coarse phase-angle detection step
custom_params.dt_capture = 5;           % [s] coarse capture detection step
custom_params.max_wait = 2*pi * sys.mu^(-0.5) / ((sys.Re + sys.h_insert)^(-1.5) - (sys.Re + sys.h_target)^(-1.5));
custom_params.max_capture_time = 30000; % [s] maximum post-burn capture search time
custom_params.phase_tol = 1e-7;         % [rad] phase-angle event tolerance
custom_params.event_time_tol = 1e-3;    % [s] event refinement tolerance
custom_params.capture_pos_tol = 0.5;    % [m] capture tolerance about desired_rel_lvlh
custom_params.min_capture_time = 0;     % [s] raise to ignore very early local minima

% Mode options: "CUSTOM_IMPULSE", "HOHMANN"; "MULTI_HOHMANN" is preliminary.
phasing_mode = "CUSTOM_IMPULSE";
[phasing_mode, custom_params] = apply_json_to_phase1(phasing_mode, custom_params, mission_cfg);
[phasing_mode, custom_params] = apply_run_config_to_phase1(phasing_mode, custom_params, run_cfg);
[phasing_mode, custom_params] = apply_phase1_env_overrides(phasing_mode, custom_params, run_cfg);
if ~isempty(fieldnames(mission_cfg)) && phasing_mode=="CUSTOM_IMPULSE" && ...
        (~has_json_path(mission_cfg,{'phase1','delta_v_m_s'}) || ...
        ~(has_json_path(mission_cfg,{'phase1','phase_angle_deg'}) || has_json_path(mission_cfg,{'phase1','phase_angle_rad'})) || ...
        ~(has_json_path(mission_cfg,{'phase1','gamma_deg'}) || has_json_path(mission_cfg,{'phase1','gamma_rad'})))
    error('mission:IncompleteManeuverDesign','Optimizer artifact lacks explicit custom manoeuvre parameters.');
end
if isempty(fieldnames(mission_cfg)) && phasing_mode=="CUSTOM_IMPULSE" && ...
        (~has_nonempty_run_value(overrides,{'phase1','delta_v_m_s'}) || ...
        ~(has_nonempty_run_value(overrides,{'phase1','phase_angle_deg'}) || has_nonempty_run_value(overrides,{'phase1','phase_angle_rad'})) || ...
        ~(has_nonempty_run_value(overrides,{'phase1','gamma_deg'}) || has_nonempty_run_value(overrides,{'phase1','gamma_rad'})))
    error('mission:MissingManeuverDesign','CUSTOM_IMPULSE without an archive requires explicit phase angle, delta-V and gamma. Historical fallback numbers are not a new design.');
end


p2 = default_phase2_config();
% Phase 2 settings are local configuration, not Python authority.
p2 = apply_run_config_to_phase2(p2, run_cfg);
p2.mode = upper(string(run_cfg.phase2.mode));
p2.autonomous = run_cfg.phase2.autonomous;
p3 = default_phase3_config();
% Phase 3 settings are local configuration, not Python authority.
p3 = apply_run_config_to_phase3(p3, run_cfg);
p3.apogee_burns = run_cfg.phase3.apogee_burns;
p3 = apply_phase3_env_overrides(p3, run_cfg);
if p3.mode ~= "HOHMANN"
    error('mission:UnsupportedDeorbitMode', 'Phase 3 supports only HOHMANN direct descent.');
end
cfg = struct('system', sys_orbit, 'proximity_system', sys, ...
    'run', run_cfg, 'optimizer', mission_cfg, 'phase1_mode', phasing_mode, ...
    'phase1', custom_params, 'phase2', p2, 'phase3', p3, ...
    'deorbit', apply_phase3_config_to_params(custom_params, p3));
cfg.provenance=struct('reference',sys.reference,'run_overrides',overrides, ...
    'environment_enabled',run_cfg.runtime.allow_environment_overrides);
cfg.contract=mission.physics_contract(sys_orbit,run_cfg);
cfg.deorbit.compatibility=cfg.contract;
mission.validate_optimizer_compatibility(mission_cfg,cfg.contract,run_cfg,sys.reference.preset);
mission.validate_configuration(cfg);
end

function sys = apply_run_config_to_sys(sys, run_cfg)
    sys.reentry_vehicle.aoa_profile=run_cfg.reentry.aoa_profile;
    sys.h_entry_interface = get_run_number_field(run_cfg, {'phase3','entry_interface_altitude_km'}, sys.h_entry_interface/1e3) * 1e3;
    sys.reentry_flight_path_angle = deg2rad(get_run_number_field(run_cfg, {'phase3','flight_path_angle_deg'}, rad2deg(sys.reentry_flight_path_angle)));

    sys.maneuver.default_burn_model = get_run_string_field(run_cfg, {'maneuver','burn_model'}, sys.maneuver.default_burn_model);
    sys.maneuver.finite_burn_thrust = get_run_number_field(run_cfg, {'maneuver','finite_burn_thrust_N'}, sys.maneuver.finite_burn_thrust);
    sys.maneuver.finite_burn_isp = get_run_number_field(run_cfg, {'maneuver','finite_burn_isp_s'}, sys.maneuver.finite_burn_isp);
    sys.maneuver.finite_burn_dt = get_run_number_field(run_cfg, {'maneuver','finite_burn_dt_s'}, sys.maneuver.finite_burn_dt);
    sys.maneuver.max_single_burn_duration = get_run_number_field(run_cfg, {'maneuver','max_single_burn_duration_s'}, sys.maneuver.max_single_burn_duration);
    sys.maneuver.max_single_burn_delta_v = get_run_number_field(run_cfg, {'maneuver','max_single_burn_delta_v_m_s'}, sys.maneuver.max_single_burn_delta_v);

    sys.reentry_vehicle.vehicle_mode = get_run_string_field(run_cfg, {'reentry','vehicle_mode'}, sys.reentry_vehicle.vehicle_mode);
    sys.reentry_vehicle.selected_shape = get_run_string_field(run_cfg, {'reentry','shape'}, sys.reentry_vehicle.selected_shape);
    sys.reentry_vehicle.dt = get_run_number_field(run_cfg, {'reentry','dt_s'}, sys.reentry_vehicle.dt);
    sys.reentry_vehicle.max_time = get_run_number_field(run_cfg, {'reentry','max_time_s'}, sys.reentry_vehicle.max_time);
    sys.reentry_vehicle.terminal_altitude = get_run_number_field(run_cfg, {'reentry','terminal_altitude_m'}, sys.reentry_vehicle.terminal_altitude);
    sys.reentry_vehicle.lift_enabled = get_run_bool_field(run_cfg, {'reentry','lift_enabled'}, sys.reentry_vehicle.lift_enabled);
    sys.reentry_vehicle.gravity_model = get_run_string_field(run_cfg, {'reentry','gravity_model'}, sys.reentry_vehicle.gravity_model);
    if has_run_path(run_cfg, {'reentry','aoa_deg'}) && ~isempty(get_run_value(run_cfg, {'reentry','aoa_deg'}, []))
        sys.reentry_vehicle.aoa_deg = get_run_number_field(run_cfg, {'reentry','aoa_deg'}, 20);
    end
    sys.reentry_vehicle.bank_angle_deg = get_run_number_field(run_cfg, {'reentry','bank_angle_deg'}, sys.reentry_vehicle.bank_angle_deg);
    sys.reentry_vehicle.los_margin_altitude = get_run_number_field(run_cfg, {'reentry','los_margin_altitude_m'}, sys.reentry_vehicle.los_margin_altitude);
    sys.reentry_vehicle.capsule.mass_kg = get_run_number_field(run_cfg, {'reentry','capsule','mass_kg'}, sys.reentry_vehicle.capsule.mass_kg);
    sys.reentry_vehicle.capsule.add_to_chaser_initial_mass = get_run_bool_field(run_cfg, {'reentry','capsule','add_to_chaser_initial_mass'}, sys.reentry_vehicle.capsule.add_to_chaser_initial_mass);
    sys.reentry_vehicle.capsule.separation_mode = get_run_string_field(run_cfg, {'reentry','capsule','separation_mode'}, sys.reentry_vehicle.capsule.separation_mode);
    sys.reentry_vehicle.capsule.use_paper_entry_conditions = get_run_bool_field(run_cfg, {'reentry','capsule','use_paper_entry_conditions'}, sys.reentry_vehicle.capsule.use_paper_entry_conditions);
    sys.reentry_vehicle.capsule.altitude_termination_enabled = get_run_bool_field(run_cfg, {'reentry','capsule','altitude_termination_enabled'}, sys.reentry_vehicle.capsule.altitude_termination_enabled);
    sys.reentry_vehicle.spaceplane.communication.enabled = get_run_bool_field(run_cfg, {'reentry','communication','enabled'}, sys.reentry_vehicle.spaceplane.communication.enabled);
    sys.reentry_vehicle.spaceplane.communication.relay_mode = get_run_string_field(run_cfg, {'reentry','communication','relay_mode'}, sys.reentry_vehicle.spaceplane.communication.relay_mode);
    sys.reentry_vehicle.spaceplane.communication.antenna_mount = get_run_string_field(run_cfg, {'reentry','communication','antenna_mount'}, sys.reentry_vehicle.spaceplane.communication.antenna_mount);
    sys.reentry_vehicle.spaceplane.communication.beam_half_angle_deg = get_run_number_field(run_cfg, {'reentry','communication','beam_half_angle_deg'}, sys.reentry_vehicle.spaceplane.communication.beam_half_angle_deg);
    sys.reentry_vehicle.spaceplane.communication.min_range_m = get_run_number_field(run_cfg, {'reentry','communication','min_range_m'}, sys.reentry_vehicle.spaceplane.communication.min_range_m);
    sys.reentry_vehicle.spaceplane.communication.max_range_m = get_run_number_field(run_cfg, {'reentry','communication','max_range_m'}, sys.reentry_vehicle.spaceplane.communication.max_range_m);
    sys.reentry_vehicle.spaceplane.communication.tracking_scope = get_run_string_field(run_cfg, {'reentry','communication','tracking_scope'}, sys.reentry_vehicle.spaceplane.communication.tracking_scope);
    sys.reentry_vehicle.spaceplane.communication.evaluate_bank_feasibility = get_run_bool_field(run_cfg, {'reentry','communication','evaluate_bank_feasibility'}, sys.reentry_vehicle.spaceplane.communication.evaluate_bank_feasibility);
    sys.reentry_vehicle.spaceplane.communication.earth_fixed_to_eci_angle_at_mission_epoch_deg = ...
        get_run_number_field(run_cfg, ...
            {'reentry','communication','earth_fixed_to_eci_angle_at_mission_epoch_deg'}, ...
            sys.reentry_vehicle.spaceplane.communication.earth_fixed_to_eci_angle_at_mission_epoch_deg);
    sys.reentry_vehicle.uncertainty.density_scale = get_run_number_field(run_cfg, {'reentry','uncertainty','density_scale'}, sys.reentry_vehicle.uncertainty.density_scale);
    sys.reentry_vehicle.uncertainty.cd_scale = get_run_number_field(run_cfg, {'reentry','uncertainty','cd_scale'}, sys.reentry_vehicle.uncertainty.cd_scale);
    sys.reentry_vehicle.uncertainty.ld_scale = get_run_number_field(run_cfg, {'reentry','uncertainty','ld_scale'}, sys.reentry_vehicle.uncertainty.ld_scale);
    if sys.reentry_vehicle.capsule.use_paper_entry_conditions
        error('mission:PrescribedIntegratedEntry','Paper entry conditions belong to standalone studies. Set explicit deorbit targets instead.');
    end

    if has_run_path(run_cfg, {'environment','atmospheric_drag'})
        drag = run_cfg.environment.atmospheric_drag;
        sys.environment.atmospheric_drag.enabled = get_run_bool_field(run_cfg, {'environment','atmospheric_drag','enabled'}, sys.environment.atmospheric_drag.enabled);
        sys.environment.atmospheric_drag.model = get_run_string_field(run_cfg, {'environment','atmospheric_drag','model'}, sys.environment.atmospheric_drag.model);
        sys.environment.atmospheric_drag.use_matlab_atmosisa = get_run_bool_field(run_cfg, {'environment','atmospheric_drag','use_matlab_atmosisa'}, sys.environment.atmospheric_drag.use_matlab_atmosisa);
        sys.environment.atmospheric_drag.co_rotate_atmosphere = get_run_bool_field(run_cfg, {'environment','atmospheric_drag','co_rotate_atmosphere'}, sys.environment.atmospheric_drag.co_rotate_atmosphere);
        if isfield(drag, 'earth_rotation_rad_s')
            sys.environment.atmospheric_drag.earth_rotation_rad_s = get_run_number_field(run_cfg, {'environment','atmospheric_drag','earth_rotation_rad_s'}, sys.environment.atmospheric_drag.earth_rotation_rad_s);
        end
    end
end

function sys = refresh_derived_sys(sys)
    r_insert = sys.Re + sys.h_insert;
    r_target = sys.Re + sys.h_target;
    a_transfer = 0.5 * (r_insert + r_target);
    sys.phase = pi * (1 - (a_transfer / r_target)^1.5);
end

function [phasing_mode, custom_params] = apply_run_config_to_phase1(phasing_mode, custom_params, run_cfg)
    custom_params.hohmann_method=run_cfg.phase1.hohmann_method;
    custom_params.nominal=run_cfg.phase1.nominal;
    custom_params.correction=run_cfg.phase1.correction;
    phasing_mode = get_run_string_field(run_cfg, {'phase1','mode'}, phasing_mode);
    custom_params.burn_model = get_run_string_field(run_cfg, {'maneuver','burn_model'}, custom_params.burn_model);
    custom_params.finite_burn_thrust = get_run_number_field(run_cfg, {'maneuver','finite_burn_thrust_N'}, custom_params.finite_burn_thrust);
    custom_params.finite_burn_isp = get_run_number_field(run_cfg, {'maneuver','finite_burn_isp_s'}, custom_params.finite_burn_isp);
    custom_params.dt_burn = get_run_number_field(run_cfg, {'maneuver','finite_burn_dt_s'}, custom_params.dt_burn);
    custom_params.max_single_burn_duration = get_run_number_field(run_cfg, {'maneuver','max_single_burn_duration_s'}, custom_params.max_single_burn_duration);
    custom_params.max_single_burn_delta_v = get_run_number_field(run_cfg, {'maneuver','max_single_burn_delta_v_m_s'}, custom_params.max_single_burn_delta_v);
    custom_params.use_thrust_noise = get_run_bool_field(run_cfg, {'maneuver','use_thrust_noise'}, custom_params.use_thrust_noise);
    custom_params.multi_hohmann_legs = get_run_value(run_cfg, {'maneuver','multi_hohmann_legs'}, custom_params.multi_hohmann_legs);

    if has_nonempty_run_value(run_cfg, {'phase1','phase_angle_deg'})
        custom_params.phase_angle = get_run_number_field(run_cfg, {'phase1','phase_angle_deg'}, rad2deg(custom_params.phase_angle));
        custom_params.phase_angle_unit = "deg";
    elseif has_nonempty_run_value(run_cfg, {'phase1','phase_angle_rad'})
        custom_params.phase_angle = get_run_number_field(run_cfg, {'phase1','phase_angle_rad'}, custom_params.phase_angle);
        custom_params.phase_angle_unit = "rad";
    end

    custom_params.delta_v = get_run_number_field(run_cfg, {'phase1','delta_v_m_s'}, custom_params.delta_v);
    if has_nonempty_run_value(run_cfg, {'phase1','gamma_deg'})
        custom_params.gamma = get_run_number_field(run_cfg, {'phase1','gamma_deg'}, rad2deg(custom_params.gamma));
        custom_params.gamma_unit = "deg";
    elseif has_nonempty_run_value(run_cfg, {'phase1','gamma_rad'})
        custom_params.gamma = get_run_number_field(run_cfg, {'phase1','gamma_rad'}, custom_params.gamma);
        custom_params.gamma_unit = "rad";
    end

    custom_params.desired_rel_lvlh = get_run_vector_field(run_cfg, {'phase1','desired_rel_lvlh_m'}, custom_params.desired_rel_lvlh);
    custom_params.time_step = get_run_number_field(run_cfg, {'phase1','time_step_s'}, custom_params.time_step);
    custom_params.dt_phase = get_run_number_field(run_cfg, {'phase1','dt_phase_s'}, custom_params.dt_phase);
    custom_params.dt_capture = get_run_number_field(run_cfg, {'phase1','dt_capture_s'}, custom_params.dt_capture);
    custom_params.max_wait = get_run_number_field(run_cfg, {'phase1','max_wait_s'}, custom_params.max_wait);
    custom_params.max_capture_time = get_run_number_field(run_cfg, {'phase1','max_capture_time_s'}, custom_params.max_capture_time);
    custom_params.phase_tol = get_run_number_field(run_cfg, {'phase1','phase_tol_rad'}, custom_params.phase_tol);
    custom_params.event_time_tol = get_run_number_field(run_cfg, {'phase1','event_time_tol_s'}, custom_params.event_time_tol);
    custom_params.capture_pos_tol = get_run_number_field(run_cfg, {'phase1','capture_pos_tol_m'}, custom_params.capture_pos_tol);
    custom_params.min_capture_time = get_run_number_field(run_cfg, {'phase1','min_capture_time_s'}, custom_params.min_capture_time);
end

function [phasing_mode, custom_params] = apply_phase1_env_overrides(phasing_mode, custom_params, run_cfg)
    if ~get_run_bool_field(run_cfg, {'runtime','allow_environment_overrides'}, true)
        return;
    end

    burn_model_env = strtrim(string(getenv('RENDEZVOUS_BURN_MODEL')));
    if strlength(burn_model_env) > 0
        custom_params.burn_model = upper(burn_model_env);
    end
end

function p2 = default_phase2_config()
    p2 = struct();
    p2.dt = 1.0;
    p2.S2 = [0; -5000; 0];
    p2.S3 = [NaN; NaN; NaN];
    p2.S4_R_abs = 30;
    p2.S4 = [NaN; NaN; NaN];
    p2.initial_S2_tol = 50.0;
    p2.tof_initial_s2 = 1200;
    p2.delta_R_cycloid = 400;
    p2.vbar_burn_sign = -1;
    p2.vbar_cross_tol = 1.0;
    p2.max_cycloid_orbits = 4.0;
    p2.rbar_hop_count = 8;
    p2.tof_hop = 300;
    p2.capture_pos_tol = 0.25;
    p2.max_terminal_refines = 4;
    p2.tof_terminal_refine = 180;
    p2.Isp_fallback_s = 220;
end

function p2 = apply_run_config_to_phase2(p2, run_cfg)
    p2.dt = get_run_number_field(run_cfg, {'phase2','dt_s'}, p2.dt);
    p2.S2 = get_run_vector_field(run_cfg, {'phase2','S2_m'}, p2.S2);
    p2.S4_R_abs = get_run_number_field(run_cfg, {'phase2','S4_R_abs_m'}, p2.S4_R_abs);
    p2.S4_R_abs = get_run_number_field(run_cfg, {'phase2','terminal_standoff_m'}, p2.S4_R_abs);
    p2.initial_S2_tol = get_run_number_field(run_cfg, {'phase2','initial_S2_tol_m'}, p2.initial_S2_tol);
    p2.tof_initial_s2 = get_run_number_field(run_cfg, {'phase2','tof_initial_s2_s'}, p2.tof_initial_s2);
    p2.delta_R_cycloid = get_run_number_field(run_cfg, {'phase2','delta_R_cycloid_m'}, p2.delta_R_cycloid);
    p2.vbar_burn_sign = get_run_number_field(run_cfg, {'phase2','vbar_burn_sign'}, p2.vbar_burn_sign);
    p2.vbar_cross_tol = get_run_number_field(run_cfg, {'phase2','vbar_cross_tol_m'}, p2.vbar_cross_tol);
    p2.max_cycloid_orbits = get_run_number_field(run_cfg, {'phase2','max_cycloid_orbits'}, p2.max_cycloid_orbits);
    p2.rbar_hop_count = get_run_number_field(run_cfg, {'phase2','rbar_hop_count'}, p2.rbar_hop_count);
    p2.tof_hop = get_run_number_field(run_cfg, {'phase2','tof_hop_s'}, p2.tof_hop);
    p2.capture_pos_tol = get_run_number_field(run_cfg, {'phase2','capture_pos_tol_m'}, p2.capture_pos_tol);
    p2.max_terminal_refines = get_run_number_field(run_cfg, {'phase2','max_terminal_refines'}, p2.max_terminal_refines);
    p2.tof_terminal_refine = get_run_number_field(run_cfg, {'phase2','tof_terminal_refine_s'}, p2.tof_terminal_refine);
    p2.Isp_fallback_s = get_run_number_field(run_cfg, {'phase2','Isp_fallback_s'}, p2.Isp_fallback_s);
end

function phase3_cfg = default_phase3_config()
    phase3_cfg = struct();
    phase3_cfg.mode = "HOHMANN";
    phase3_cfg.dt_reentry_coast_s = 2;
    phase3_cfg.max_reentry_coast_time_s = [];
    phase3_cfg.drag_deorbit_design_mode = "AUTO";
    phase3_cfg.drag_deorbit_design_file = "configs/latest_drag_deorbit_solution.json";
    phase3_cfg.drag_deorbit_delta_v_m_s = [];
    phase3_cfg.drag_deorbit_max_coast_time_s = [];
end

function phase3_cfg = apply_run_config_to_phase3(phase3_cfg, run_cfg)
    phase3_cfg.mode = get_run_string_field(run_cfg, {'phase3','mode'}, phase3_cfg.mode);
    phase3_cfg.dt_reentry_coast_s = get_run_number_field(run_cfg, {'phase3','dt_reentry_coast_s'}, phase3_cfg.dt_reentry_coast_s);
    phase3_cfg.max_reentry_coast_time_s = get_run_number_field(run_cfg, {'phase3','max_reentry_coast_time_s'}, phase3_cfg.max_reentry_coast_time_s);
    phase3_cfg.drag_deorbit_design_mode = get_run_string_field(run_cfg, {'phase3','drag_deorbit_design','mode'}, phase3_cfg.drag_deorbit_design_mode);
    phase3_cfg.drag_deorbit_design_file = get_run_string_field(run_cfg, {'phase3','drag_deorbit_design','file'}, phase3_cfg.drag_deorbit_design_file);
    phase3_cfg.drag_deorbit_delta_v_m_s = get_run_number_field(run_cfg, {'phase3','drag_deorbit_design','delta_v_m_s'}, phase3_cfg.drag_deorbit_delta_v_m_s);
    phase3_cfg.drag_deorbit_max_coast_time_s = get_run_number_field(run_cfg, {'phase3','drag_deorbit_design','max_coast_time_s'}, phase3_cfg.drag_deorbit_max_coast_time_s);
end

function phase3_cfg = apply_phase3_env_overrides(phase3_cfg, run_cfg)
    if ~get_run_bool_field(run_cfg, {'runtime','allow_environment_overrides'}, true)
        return;
    end

    reentry_mode_env = getenv('RENDEZVOUS_PHASE3_MODE');
    if strlength(reentry_mode_env) > 0
        phase3_cfg.mode = string(reentry_mode_env);
    end

end

function custom_params = apply_phase3_config_to_params(custom_params, phase3_cfg)
    custom_params.apogee_burns = phase3_cfg.apogee_burns;
    custom_params.dt_reentry_coast = phase3_cfg.dt_reentry_coast_s;
    custom_params.drag_deorbit_design_mode = phase3_cfg.drag_deorbit_design_mode;
    custom_params.drag_deorbit_design_file = phase3_cfg.drag_deorbit_design_file;
    custom_params.drag_deorbit_delta_v_m_s = phase3_cfg.drag_deorbit_delta_v_m_s;
    custom_params.drag_deorbit_max_coast_time_s = phase3_cfg.drag_deorbit_max_coast_time_s;
    if ~isempty(phase3_cfg.max_reentry_coast_time_s)
        custom_params.max_reentry_coast_time = phase3_cfg.max_reentry_coast_time_s;
    end
end

function tf = has_nonempty_run_value(s, path)
    tf = has_run_path(s, path) && ~isempty(get_run_value(s, path, []));
end

function value = get_run_number_field(s, path, default_value)
    value = get_run_value(s, path, default_value);
    if ischar(value) || isstring(value)
        value = str2double(value);
    end
    if isempty(value) || ~isnumeric(value) || ~isscalar(value) || isnan(value)
        value = default_value;
    end
end

function vec = get_run_vector_field(s, path, default_value)
    vec = get_run_value(s, path, default_value);
    if isempty(vec)
        vec = default_value;
    end
    vec = vec(:);
    if numel(vec) ~= numel(default_value) || ~isnumeric(vec) || any(~isfinite(vec))
        vec = default_value(:);
    end
end

function sys = apply_environment_env_overrides(sys, run_cfg)
    if nargin < 2
        run_cfg = struct();
    end
    if ~get_run_bool_field(run_cfg, {'runtime','allow_environment_overrides'}, true)
        return;
    end

    drag_model_env = strtrim(string(getenv('RENDEZVOUS_ATMOSPHERIC_DRAG')));
    if strlength(drag_model_env) > 0
        if upper(drag_model_env) == "OFF" || upper(drag_model_env) == "NONE" || upper(drag_model_env) == "0"
            sys.environment.atmospheric_drag.enabled = false;
        else
            sys.environment.atmospheric_drag.enabled = true;
            sys.environment.atmospheric_drag.model = upper(drag_model_env);
        end
    end

    reentry_shape_env = strtrim(string(getenv('RENDEZVOUS_REENTRY_SHAPE')));
    if strlength(reentry_shape_env) > 0
        sys.reentry_vehicle.selected_shape = upper(reentry_shape_env);
    end
end

function print_environment_config(sys)
    fprintf('Scenario (Mission_Config.m): insertion %.1f km, target %.1f km\n', ...
            sys.h_insert/1000, sys.h_target/1000);
    fprintf('Maneuver model: %s, thrust %.1f N, Isp %.1f s\n', ...
            char(string(sys.maneuver.default_burn_model)), sys.maneuver.finite_burn_thrust, sys.maneuver.finite_burn_isp);
    fprintf('Phase 3 geometry: entry interface %.1f km, FPA %.2f deg\n', ...
            sys.h_entry_interface/1000, rad2deg(sys.reentry_flight_path_angle));
    drag = sys.environment.atmospheric_drag;
    if drag.enabled
        fprintf('Environment: orbital atmospheric drag ON (%s), Cd/A chaser %.2f/%.2f m^2, target %.2f/%.2f m^2\n', ...
                char(string(drag.model)), drag.chaser_cd, drag.chaser_area_m2, drag.target_cd, drag.target_area_m2);
    else
        fprintf('Environment: orbital atmospheric drag OFF\n');
    end
    reentry_shape = string(sys.reentry_vehicle.selected_shape);
    if upper(string(sys.reentry_vehicle.vehicle_mode)) == "CAPSULE"
        reentry_shape = "CAPSULE";
    end
    if upper(string(sys.reentry_vehicle.vehicle_mode)) == "CAPSULE" && ...
            ~sys.reentry_vehicle.capsule.altitude_termination_enabled
        fprintf(['Re-entry vehicle: mode %s, shape %s, nominal stop %.1f m/s, ' ...
                 'ground safety %.1f km, lift model %s, entry atmosphere ISA76\n'], ...
                char(string(sys.reentry_vehicle.vehicle_mode)), char(reentry_shape), ...
                sys.reentry_vehicle.capsule.parachute_deploy_speed_m_s, ...
                sys.reentry_vehicle.capsule.safety_floor_altitude_m/1000, ...
                char(bool_label(sys.reentry_vehicle.lift_enabled)));
    else
        fprintf('Re-entry vehicle: mode %s, shape %s, terminal altitude %.1f km, lift model %s, entry atmosphere ISA76\n', ...
                char(string(sys.reentry_vehicle.vehicle_mode)), char(reentry_shape), ...
                sys.reentry_vehicle.terminal_altitude/1000, ...
                char(bool_label(sys.reentry_vehicle.lift_enabled)));
    end
    communication = sys.reentry_vehicle.spaceplane.communication;
    if upper(string(communication.relay_mode)) == ...
            "PAPER_TDRS_STATIC_EARTH_FIXED"
        fprintf(['Paper TDRS ECEF->ECI convention: Greenwich angle at ' ...
                 'mission epoch %.6f deg\n'], ...
            communication.earth_fixed_to_eci_angle_at_mission_epoch_deg);
    end
end

function sys = apply_pre_berthing_drag_scope(sys, run_cfg)
    if drag_starts_after_berthing(run_cfg) && orbital_drag_enabled(sys)
        sys.environment.atmospheric_drag.enabled = false;
        fprintf('Environment scope: orbital atmospheric drag held OFF through Phase 1/2; enabled after berthing.\n');
    end
end

function warn_if_mission_json_environment_mismatch(cfg, sys)
    if isempty(fieldnames(cfg)) || ~has_json_path(cfg, {'environment','atmospheric_drag'})
        return;
    end

    json_drag_enabled = get_json_bool(cfg, {'environment','atmospheric_drag','enabled'}, false);
    json_drag_model = upper(get_json_string(cfg, {'environment','atmospheric_drag','model'}, "ISA76"));
    sys_drag = sys.environment.atmospheric_drag;
    sys_drag_enabled = parse_bool_setting(sys_drag.enabled);
    sys_drag_model = upper(string(sys_drag.model));

    if json_drag_enabled ~= sys_drag_enabled || json_drag_model ~= sys_drag_model
        fprintf(['WARNING: selected mission JSON atmospheric-drag setting (%s/%s) does not match ' ...
                 'current MATLAB setting (%s/%s). Regenerate or pin a matching Python Phase 1 JSON for consistent drag-on runs.\n'], ...
                bool_label(json_drag_enabled), char(json_drag_model), ...
                bool_label(sys_drag_enabled), char(sys_drag_model));
    end
end

function [phasing_mode, custom_params] = apply_json_to_phase1(phasing_mode, custom_params, cfg)
    if isempty(fieldnames(cfg)) || ~isfield(cfg, 'phase1')
        return;
    end

    phasing_mode = get_json_string(cfg, {'phase1','mode'}, phasing_mode);
    custom_params.burn_model = get_json_string(cfg, {'phase1','burn_model'}, custom_params.burn_model);

    if has_json_path(cfg, {'phase1','phase_angle_deg'})
        custom_params.phase_angle = get_json_number(cfg, {'phase1','phase_angle_deg'}, custom_params.phase_angle);
        custom_params.phase_angle_unit = "deg";
    elseif has_json_path(cfg, {'phase1','phase_angle_rad'})
        custom_params.phase_angle = get_json_number(cfg, {'phase1','phase_angle_rad'}, custom_params.phase_angle);
        custom_params.phase_angle_unit = "rad";
    end

    if has_json_path(cfg, {'phase1','gamma_deg'})
        custom_params.gamma = get_json_number(cfg, {'phase1','gamma_deg'}, custom_params.gamma);
        custom_params.gamma_unit = "deg";
    elseif has_json_path(cfg, {'phase1','gamma_rad'})
        custom_params.gamma = get_json_number(cfg, {'phase1','gamma_rad'}, custom_params.gamma);
        custom_params.gamma_unit = "rad";
    end

    custom_params.delta_v = get_json_number(cfg, {'phase1','delta_v_m_s'}, custom_params.delta_v);
    custom_params.desired_rel_lvlh = get_json_vector(cfg, {'phase1','desired_rel_lvlh_m'}, custom_params.desired_rel_lvlh);

    custom_params.finite_burn_thrust = get_json_number(cfg, {'maneuver','finite_burn_thrust_N'}, custom_params.finite_burn_thrust);
    custom_params.finite_burn_isp = get_json_number(cfg, {'maneuver','finite_burn_isp_s'}, custom_params.finite_burn_isp);
    custom_params.dt_burn = get_json_number(cfg, {'maneuver','finite_burn_dt_s'}, custom_params.dt_burn);
    custom_params.max_single_burn_duration = get_json_number(cfg, {'maneuver','max_single_burn_duration_s'}, custom_params.max_single_burn_duration);
    custom_params.max_single_burn_delta_v = get_json_number(cfg, {'maneuver','max_single_burn_delta_v_m_s'}, custom_params.max_single_burn_delta_v);

    custom_params.time_step = get_json_number(cfg, {'phase1','time_step_s'}, custom_params.time_step);
    custom_params.dt_phase = get_json_number(cfg, {'phase1','dt_phase_s'}, custom_params.dt_phase);
    custom_params.dt_capture = get_json_number(cfg, {'phase1','dt_capture_s'}, custom_params.dt_capture);
    custom_params.max_wait = get_json_number(cfg, {'phase1','max_wait_s'}, custom_params.max_wait);
    custom_params.max_capture_time = get_json_number(cfg, {'phase1','max_capture_time_s'}, custom_params.max_capture_time);
    custom_params.phase_tol = get_json_number(cfg, {'phase1','phase_tol_rad'}, custom_params.phase_tol);
    custom_params.event_time_tol = get_json_number(cfg, {'phase1','event_time_tol_s'}, custom_params.event_time_tol);
    custom_params.capture_pos_tol = get_json_number(cfg, {'phase1','capture_pos_tol_m'}, custom_params.capture_pos_tol);
    custom_params.min_capture_time = get_json_number(cfg, {'phase1','min_capture_time_s'}, custom_params.min_capture_time);
end

function value = get_json_vector(cfg, path, default_value)
    value = get_json_value(cfg, path, default_value);
    value = value(:);
    if numel(value) ~= numel(default_value) || ~isnumeric(value)
        value = default_value;
    end
end
