function c=correction_defaults()
% Explicit exploratory errors; independent of caller RNG and legacy noise.
c=struct('enabled',false,'corrections_enabled',true,'seed',42, ...
    'state_knowledge',"PERFECT_INSTANTANEOUS", ...
    'position_sigma_m',[20;20;20],'velocity_sigma_m_s',[.02;.02;.02], ...
    'burn_gain_sigma',.002,'burn_pointing_sigma_rad',.0002, ...
    'opportunity_fractions',[.35 .75],'terminal_velocity_cleanup',true, ...
    'max_corrections',3,'max_correction_delta_v_m_s',2, ...
    'max_total_correction_delta_v_m_s',3,'max_nominal_burn_m_s',150, ...
    'max_propellant_kg',400,'minimum_mass_kg',1000,'max_elapsed_s',40000, ...
    'minimum_remaining_transfer_s',120,'max_iterations',6,'max_evaluations',30, ...
    'max_runtime_s',60);
end
