function [X_entry, info] = entry_interface(hist, X_terminal, sys, target_altitude)
%ENTRY_INTERFACE Accept the propagated terminal event; never impose FPA/state.
% All active deorbit propagators refine their own altitude event. A nearest
% sample, an interpolated straight chord, or an empty fallback is not an event.
if ~isfield(hist,'pos') || isempty(hist.pos) || ~isfield(hist,'vel') || ...
        isempty(hist.vel) || ~isfield(hist,'time') || isempty(hist.time)
    error('mission:MissingEntryHistory','A propagated entry event history is required.');
end
if abs(norm(X_terminal(1:3))-sys.Re-target_altitude)>1e-3 || ...
        dot(X_terminal(1:3),X_terminal(4:6))>=0
    error('mission:NoEntryCrossing','Terminal state is not a descending interface event within 1 mm.');
end
if norm(hist.pos(:,end)-X_terminal(1:3))>1e-6 || ...
        norm(hist.vel(:,end)-X_terminal(4:6))>1e-8 || ...
        ~isfield(hist,'mass') || abs(hist.mass(end)-X_terminal(14))>1e-8
    error('mission:EntryHistoryMismatch','Terminal history and propagated state disagree.');
end
X_entry=X_terminal;
a=mission.state_record(X_entry,sys,hist.time(end),"PROPAGATED_DEORBIT_TERMINAL");
info=struct('time_s',hist.time(end),'altitude_m',a.altitude_spherical_m, ...
    'velocity_m_s',a.speed_inertial_m_s,'fpa_deg',a.fpa_inertial_deg, ...
    'achieved',a,'requested',struct('altitude_m',target_altitude, ...
    'fpa_inertial_deg',-abs(rad2deg(sys.reentry_flight_path_angle))), ...
    'method',"PROPAGATED_EVENT_NO_STATE_RESET",'crossing_verified',true);
info.fpa_error_deg=a.fpa_inertial_deg-info.requested.fpa_inertial_deg;
end
