function p=nominal_defaults()
% Integration accuracy, targeting acceptance and work bounds are distinct.
p=struct('position_tolerance_m',.5,'velocity_tolerance_m_s',.001, ...
    'desired_velocity_lvlh_m_s',[0;0;0],'relative_tolerance',1e-11, ...
    'position_absolute_tolerance_m',1e-4,'velocity_absolute_tolerance_m_s',1e-7, ...
    'max_step_s',60,'max_iterations',8,'max_evaluations',40, ...
    'max_runtime_s',60,'difference_step_m_s',.01,'max_update_m_s',25);
end
