function report(result)
%REPORT Print diagnostics separately from propagation and visualization.
reentry_atmo_info = result.entry.summary;
Budget = result.budget;
active_vehicle_mass_kg = reentry_atmo_info.active_vehicle_mass_kg;
total_accounted_mass_kg = reentry_atmo_info.total_accounted_mass_kg;
fprintf('   vehicle mode: %s, shape: %s\n', ...
        char(reentry_atmo_info.vehicle_mode), char(reentry_atmo_info.shape_name));
    fprintf('   entry duration: %.2f s, final altitude: %.2f km, termination: %s\n', ...
            reentry_atmo_info.duration_s, reentry_atmo_info.final_altitude_m/1000, ...
            char(reentry_atmo_info.termination_reason));
    if ~reentry_atmo_info.completed_nominally
        warning('Atmospheric entry ended without a nominal terminal event (reason: %s, minimum altitude: %.2f km).', ...
                char(reentry_atmo_info.termination_reason), reentry_atmo_info.minimum_altitude_m/1000);
    end
    fprintf('   AoA %.2f deg, bank %.2f deg, inertial FPA %.3f -> %.3f deg\n', ...
            reentry_atmo_info.aoa_deg, reentry_atmo_info.bank_angle_deg, ...
            reentry_atmo_info.initial_fpa_deg, reentry_atmo_info.final_fpa_deg);
    fprintf('   atmosphere-relative FPA %.3f -> %.3f deg, beta %.3f kg/m^2\n', ...
            reentry_atmo_info.initial_fpa_rel_deg, reentry_atmo_info.final_fpa_rel_deg, ...
            reentry_atmo_info.ballistic_coefficient_kg_m2);
fprintf('   surrogate heat model %s: max %.3f W/cm^2, total %.3f MJ/m^2\n', ...
        char(reentry_atmo_info.heating_model), ...
        reentry_atmo_info.max_heat_flux_W_m2/1e4, reentry_atmo_info.total_heat_load_J_m2/1e6);
if isfinite(reentry_atmo_info.reference_total_heat_load_J_m2)
    if reentry_atmo_info.heat_constraint_comparable
        fprintf('   paper shallow-entry heat-load reference: %.3f MJ/m^2, exceeded: %s\n', ...
                reentry_atmo_info.reference_total_heat_load_J_m2/1e6, ...
                char(bool_label(reentry_atmo_info.exceeds_reference_total_heat_load)));
    else
        fprintf(['   paper shallow-entry heat-load reference: %.3f MJ/m^2; direct ' ...
                 'pass/fail not evaluated (%s differs from %s)\n'], ...
                reentry_atmo_info.reference_total_heat_load_J_m2/1e6, ...
                char(reentry_atmo_info.heating_model), ...
                char(reentry_atmo_info.paper_heating_model));
    end
end
fprintf('   max dynamic pressure: %.3f kPa, max aero g-load: %.3f g\n', ...
        reentry_atmo_info.max_dynamic_pressure_Pa/1e3, reentry_atmo_info.max_g_load);
fprintf('   LOS maintained: %s, min Earth-limb clearance: %.2f km, min elevation: %.2f deg\n', ...
        char(bool_label(reentry_atmo_info.los_maintained)), ...
        reentry_atmo_info.min_los_clearance_m/1000, reentry_atmo_info.min_los_elevation_deg);
if ~reentry_atmo_info.los_maintained
    fprintf('   first LOS loss after entry interface: %.2f s\n', reentry_atmo_info.first_los_loss_time_s);
end
if reentry_atmo_info.antenna_evaluated
    fprintf('   target antenna: min/max RAAP %.2f/%.2f deg, range %.1f-%.1f km, beam half-angle %.2f deg, tracking maintained: %s\n', ...
            reentry_atmo_info.min_raap_deg, reentry_atmo_info.max_raap_deg, ...
            reentry_atmo_info.min_relay_range_m/1e3, reentry_atmo_info.max_relay_range_m/1e3, ...
            reentry_atmo_info.antenna_beam_half_angle_deg, ...
            char(bool_label(reentry_atmo_info.antenna_tracking_maintained)));
    if reentry_atmo_info.antenna_bank_scan_enabled
        fprintf(['   instantaneous bank-only geometric scan: max best RAAP %.2f deg, ' ...
                 'reachable at each sample: %s\n'], ...
                reentry_atmo_info.max_instantaneous_best_raap_deg, ...
                char(bool_label(reentry_atmo_info.instantaneous_bank_geometric_reachable)));
    else
        fprintf('   instantaneous bank-only geometric scan: disabled (not evaluated)\n');
    end
end
if reentry_atmo_info.any_evaluated_constraint_violated
    warning(['One or more evaluated reduced-order re-entry constraints were violated. ' ...
             'This includes active antenna geometry when configured.']);
end
if ~reentry_atmo_info.all_configured_constraints_evaluated
    fprintf(['   constraint status: incomplete; paper heat compliance is not ' ...
             'claimed for the configured surrogate model.\n']);
end

%% 5. Summary and Output
disp(' ');
disp('=== Final Mission Delta-V & Mass Budget ===');
disp(Budget);
fprintf('Total Delta-V required: %.2f m/s\n', sum(Budget.DeltaV_ms));
fprintf('Total Fuel consumed:    %.2f kg\n', sum(Budget.Fuel_Consumed_kg));
fprintf('Active propagated mass: %.2f kg\n', active_vehicle_mass_kg);
fprintf('Total accounted mass:   %.2f kg\n', total_accounted_mass_kg);

end

